import type { Metadata } from "next";
import { Overpass, Roboto } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ToTop from "@/components/subc/ToTop";

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
  // weights comuns (pode ajustar se quiser)
  weight: ["300", "400", "500", "600", "700", "800"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Prime Health - Academia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${overpass.variable} ${roboto.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
        <ToTop />
      </body>
    </html>
  );
}
